<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{asset('frontEnd/css/open-iconic-bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/animate.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/owl.theme.default.min.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/aos.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/bootstrap-datepicker.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/jquery.timepicker.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/icomoon.css')}}">
<link rel="stylesheet" href="{{asset('frontEnd/css/style.css')}}">
